-- V1__init_schema.sql
-- 玑衡AI PostgreSQL 初始 schema（snake_case 命名）

-- 用户表
CREATE TABLE user_account (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone           VARCHAR(20) UNIQUE NOT NULL,
    password_hash   VARCHAR(100),
    display_name    VARCHAR(50),
    avatar          VARCHAR(255),
    plan            VARCHAR(20) DEFAULT 'basic',
    department      VARCHAR(50),
    points          INT DEFAULT 0,
    phone_bound     BOOLEAN DEFAULT TRUE,
    data_scopes     VARCHAR(100),
    locale          VARCHAR(10) DEFAULT 'zh_CN',
    notify_on       BOOLEAN DEFAULT TRUE,
    status          VARCHAR(20) DEFAULT 'verified',
    last_login_at   TIMESTAMPTZ,
    last_login_ip   VARCHAR(50),
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    version         INT DEFAULT 0
);

-- 技能表
CREATE TABLE skill (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    description     VARCHAR(500),
    kind            VARCHAR(20) NOT NULL,
    prompt_template TEXT,
    toolset         VARCHAR(500),
    sort_order      INT,
    run_count       INT DEFAULT 0,
    creator_id      BIGINT,
    last_edited_at  TIMESTAMPTZ,
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 用户技能开关关联表
CREATE TABLE user_skill (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    skill_id        BIGINT NOT NULL,
    enabled         BOOLEAN DEFAULT FALSE,
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, skill_id)
);

-- 专家表
CREATE TABLE expert (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expert_id           VARCHAR(50) UNIQUE NOT NULL,
    name                VARCHAR(100) NOT NULL,
    initial             VARCHAR(10),
    avatar_bg           VARCHAR(20),
    description         VARCHAR(500),
    system_prompt_ref   VARCHAR(255),
    toolset             VARCHAR(500),
    sort_order          INT,
    config_version      INT DEFAULT 1,
    created_at          TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 报告表
CREATE TABLE report (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id               VARCHAR(50) UNIQUE NOT NULL,
    user_id                 BIGINT NOT NULL,
    kind                    VARCHAR(30) NOT NULL,
    title                   VARCHAR(200) NOT NULL,
    summary                 VARCHAR(500),
    content                 TEXT,
    state                   VARCHAR(20) DEFAULT 'completed',
    pages                   INT,
    ref_count               INT DEFAULT 0,
    refs                    TEXT,
    source_conversation_id  VARCHAR(50),
    created_at              TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 定时任务表
CREATE TABLE scheduled_task (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id         VARCHAR(50) UNIQUE NOT NULL,
    user_id         BIGINT NOT NULL,
    type            VARCHAR(20) NOT NULL,
    cron            VARCHAR(100),
    condition_expr  TEXT,
    payload         TEXT,
    next_run_at     TIMESTAMPTZ,
    last_result     TEXT,
    last_trigger_at TIMESTAMPTZ,
    status          VARCHAR(20) DEFAULT 'active',
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 通知表
CREATE TABLE notification (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id VARCHAR(50) UNIQUE NOT NULL,
    user_id         BIGINT NOT NULL,
    type            VARCHAR(30) NOT NULL,
    title           VARCHAR(200),
    content         TEXT,
    is_read         BOOLEAN DEFAULT FALSE,
    task_id         VARCHAR(50),
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 埋点事件表
CREATE TABLE event_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT,
    event           VARCHAR(50) NOT NULL,
    timestamp       TIMESTAMPTZ NOT NULL,
    props           TEXT,
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 会话表（Python 回写，用于报告关联）
CREATE TABLE conversation (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id     VARCHAR(50) UNIQUE NOT NULL,
    conversation_uuid   VARCHAR(50) UNIQUE NOT NULL,
    user_id             BIGINT NOT NULL,
    agent_id            VARCHAR(50),
    title               VARCHAR(200),
    status              VARCHAR(20) DEFAULT 'active',
    mode                VARCHAR(20),
    expert              VARCHAR(50),
    deleted_at          TIMESTAMPTZ,
    server_id           BIGINT,
    synced_at           TIMESTAMPTZ,
    created_at          TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 导出任务表
CREATE TABLE export_task (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id         VARCHAR(50) UNIQUE NOT NULL,
    report_id       BIGINT NOT NULL,
    user_id         BIGINT NOT NULL,
    format          VARCHAR(10) NOT NULL,
    status          VARCHAR(20) DEFAULT 'pending',
    file_path       VARCHAR(255),
    error_message   TEXT,
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    completed_at    TIMESTAMPTZ
);

-- 索引
CREATE INDEX idx_user_phone ON user_account(phone);
CREATE INDEX idx_user_skill_uid ON user_skill(user_id);
CREATE INDEX idx_report_user_kind ON report(user_id, kind, created_at DESC);
CREATE INDEX idx_task_user_type ON scheduled_task(user_id, type, next_run_at);
CREATE INDEX idx_notify_user_read ON notification(user_id, is_read, created_at DESC);
CREATE INDEX idx_event_user_time ON event_log(user_id, timestamp DESC);
