-- V2__seed_skills.sql
-- 36 个官方技能种子数据（kind=official），原型列出 9 个，其余 27 个待产品补充

INSERT INTO skill (id, name, description, kind, toolset, sort_order, run_count) VALUES
(1, '有色板块深度透视', '对有色金属板块进行多维度深度分析，包含涨跌驱动、资金流向、机构观点', 'official', '["search","quote","research"]', 1, 0),
(2, '贵金属板块深度透视', '分析金银比、贵金属板块涨跌驱动因素与宏观关联', 'official', '["search","quote","research"]', 2, 0),
(3, '期货主力行为分析', '分析期货主力合约持仓变化、多空力量对比与主力意图', 'official', '["search","quote","research"]', 3, 0),
(4, '基金涨跌解读', '解读基金涨跌原因、持仓变化与风格漂移', 'official', '["search","quote","research"]', 4, 0),
(5, '期货资金流向监测', '监测期货品种资金流入流出、持仓变化与价格关系', 'official', '["search","quote","research"]', 5, 0),
(6, '期权波动率洞察', '分析期权隐含波动率曲面、期限结构与交易机会', 'official', '["search","quote","research"]', 6, 0),
(7, '期权定价计算器', '基于 Black-Scholes 等模型计算期权理论价格与希腊字母', 'official', '["quote","research"]', 7, 0),
(8, '机构持仓透视', '分析机构持仓变化、调仓方向与持仓集中度', 'official', '["search","quote","research"]', 8, 0),
(9, '期货盘中异动归因', '对期货盘中异动进行归因分析，识别驱动事件与资金行为', 'official', '["search","quote","research"]', 9, 0),
(10, '板块轮动分析', '分析板块轮动规律、强弱排名与资金迁移路径', 'official', '["search","quote","research"]', 10, 0),
(11, '个股估值诊断', '基于多模型（PE/PB/DCF/可比公司）进行个股估值诊断', 'official', '["search","quote","research"]', 11, 0),
(12, '行业景气度跟踪', '跟踪行业景气度指标、产业链供需与价格信号', 'official', '["search","quote","research"]', 12, 0),
(13, '宏观经济数据分析', '解读宏观数据（CPI/PPI/PMI/GDP）对市场的影响', 'official', '["search","quote","research"]', 13, 0),
(14, '公司基本面分析', '分析公司财务三表、盈利能力与成长性', 'official', '["search","quote","research"]', 14, 0),
(15, '研报观点聚合', '聚合多家券商研报观点，形成共识与分歧分析', 'official', '["search","research"]', 15, 0),
(16, '公告解读', '解读公司公告（业绩预告/重大事项/股权变动）的市场影响', 'official', '["search","research"]', 16, 0),
(17, '产业链映射', '梳理产业链上下游关系，识别投资机会与风险传导路径', 'official', '["search","research"]', 17, 0),
(18, '技术指标分析', '基于技术指标（MACD/RSI/KDJ/布林带）进行趋势判断', 'official', '["quote"]', 18, 0),
(19, '资金面分析', '分析北向资金、融资融券、大宗交易等资金面信号', 'official', '["search","quote","research"]', 19, 0),
(20, '市场情绪监测', '监测市场情绪指标（换手率/涨跌比/涨停数）与历史对比', 'official', '["search","quote"]', 20, 0),
(21, '组合周度复盘', '对投资组合进行周度归因分析与绩效拆解', 'official', '["search","quote","research"]', 21, 0),
(22, '客户晨会纪要', '生成晨会纪要，覆盖隔夜要闻、板块动态与关注个股', 'official', '["search","quote","research"]', 22, 0),
(23, '事件驱动分析', '分析重大事件（政策/数据/突发事件）对板块与个股的影响', 'official', '["search","quote","research"]', 23, 0),
(24, '可比公司估值', '选取可比公司进行相对估值，输出估值溢价/折价分析', 'official', '["search","quote","research"]', 24, 0),
(25, '行业竞争格局', '分析行业竞争格局、市场份额与护城河', 'official', '["search","research"]', 25, 0),
(26, '财报速览', '快速解读财报核心数据、同比环比变化与超预期分析', 'official', '["search","research"]', 26, 0),
(27, '指数成分分析', '分析指数成分股调整、权重变化与被动资金影响', 'official', '["search","quote","research"]', 27, 0),
(28, '港股通标的分析', '分析港股通标的的资金流向、AH 股溢价与投资价值', 'official', '["search","quote","research"]', 28, 0),
(29, '可转债分析', '分析可转债条款、估值与转股价值', 'official', '["search","quote","research"]', 29, 0),
(30, 'ETF 资金流分析', '分析 ETF 申赎情况、资金流向与跟踪误差', 'official', '["search","quote"]', 30, 0),
(31, '大宗商品供需', '分析大宗商品供需平衡表、库存变化与价格趋势', 'official', '["search","quote","research"]', 31, 0),
(32, '汇率影响分析', '分析汇率变动对出口型/进口型行业与公司的影响', 'official', '["search","quote","research"]', 32, 0),
(33, '政策影响推演', '推演政策变化对行业格局与公司基本面的影响路径', 'official', '["search","research"]', 33, 0),
(34, '风险预警监控', '监控个股与组合风险指标（波动率/回撤/相关性）', 'official', '["quote","research"]', 34, 0),
(35, '一致预期分析', '分析卖方一致预期与实际业绩的偏差与修正趋势', 'official', '["search","research"]', 35, 0),
(36, '行业估值比较', '比较各行业估值水平（PE/PB 分位数）与历史位置', 'official', '["search","quote","research"]', 36, 0);