-- 对话消息（conversation 表已在 V1 创建，这里只补消息表）
CREATE TABLE chat_message (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(50) NOT NULL,
    user_id         BIGINT NOT NULL,
    role            VARCHAR(20) NOT NULL,
    content         TEXT NOT NULL,
    mode            VARCHAR(20),
    expert          VARCHAR(50),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_chat_message_conversation ON chat_message(conversation_id, id);
