-- 玑衡 World：AI 生成的公司产业链关卡
CREATE TABLE world_company (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT NOT NULL,
    company_id     VARCHAR(50) NOT NULL,
    name           VARCHAR(100) NOT NULL,
    code           VARCHAR(20),
    tag            VARCHAR(100),
    kind           VARCHAR(20) NOT NULL,
    scenario_json  TEXT NOT NULL,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, company_id)
);

CREATE INDEX idx_world_company_user ON world_company(user_id, created_at);
